.github/pull_request_template.md
This pull request introduces a pull request template.
To ensure consistency across all pull request and ensure code quality this change is helpful.
=> Feature | Pull Request Template

CONTRIBUTING.md, pyproject.toml, tests/operators/test_deeponet.py, tests/operators/test_neuraloperator.py, tests/test_optuna.py
The current test suite does not differentiate between standard tests and slow tests. As a result, all tests, irrespective of their execution time, are treated equally and run in every test cycle. This leads to increased execution time, especially in local development environments. This issue aims to introduce a classification system for our tests, specifically by marking slow tests so they can be selectively run on the CI pipeline and at predetermined times, thereby optimizing the development workflow and CI pipeline efficiency.
Tests are categorized into two categories:
- Milliseconds to 1 second: Tests running in this time-frame are quick enough to allow for rapid iteration and feedback during development. They can be run frequently without significantly impacting productivity. They do …
=> Feature: Pytest Slow Mark

setup.cfg, src/continuity/transforms/__init__.py, src/continuity/transforms/compose.py, src/continuity/transforms/transform.py, tests/conftest.py, tests/transforms/fixtures.py, tests/transforms/test_compose.py, tests/transforms/test_transform.py
Transforming tensors in the setting of neural operators can have many reasons. Transformations can improve model performance, enhance generalization, enable varied input size inputs, facilitate feature extraction, reduce overfitting, improve computational efficiency, or much more. 
Currently these transformations need to be applied manually and are dependent on the implementation of the end user. The result is difficulty in implementing correct transformations and especially chained transformations are difficult to apply. This issue aims to introduce a base transformation class for all tensors.
- Transformations of tensors are currently not implemented.
- Partly addresses #38
- Introduces a transform base class.
- Introduces a Compose class which executes multiple transformations …
=> Feature: Transforms

src/continuity/transforms/__init__.py, src/continuity/transforms/scaling.py, tests/transforms/test_scaling.py
This pull request introduces a new feature for data preprocessing: Z-Normalization. Z-Normalization, also known as standardization, is a technique used to scale data so that it has a mean of 0 and a standard deviation of 1. This process is essential in many machine learning algorithms as it ensures that each feature contributes equally to the analysis, improving the performance and stability of the models.
- Addresses the need for a standardized data preprocessing step in our machine learning pipeline. The lack of a z-normalization feature has been a significant gap in our data preprocessing capabilities, leading to suboptimal performance in models sensitive to the scale of data.
- Implements Z-normalization.
- Offers alias `Standardization`.
- Offering compatibility with …
=> Feature: Normalize

src/continuity/operators/common.py
No activation function was applied after the first layer in the residual network. Also, the actual width of a network was given by width+1. Now, it correctly correspond to the width parameter.
To make the test scripts consistent to previous tests, the widths had to be adjusted by +1. Without this fix, the tests failed
=> Add activation function after first layer

src/continuity/discrete/regular_grid.py
This pr introduces the union typing also to the regular grid sampler.
- `RegularGridSampler` currently expects only `torch.Tensor` types.
- Changes the input type to also accept lists.
- Feature is already tested in the tests for the box-sampler.
=> Bugfix: RegularGridSampler input type

CHANGELOG.md, examples/superresolution.ipynb, examples/training.ipynb, src/continuity/data/__init__.py, src/continuity/data/dataset.py, src/continuity/operators/__init__.py, src/continuity/operators/belnet.py, src/continuity/operators/deep_neural_operator.py, src/continuity/operators/deeponet.py, src/continuity/operators/integralkernel.py, src/continuity/operators/neuraloperator.py, src/continuity/operators/shape.py, tests/data/function/test_function_dataset.py, tests/operators/test_integralkernel.py, tests/operators/test_neuraloperator.py
#Cleanup: Generalize neural operator and introduce OperatorShapes
- NeuralOperator hard codes integral kernel operation.
- Fixes #96 and #55
- NeuralOperator now takes a list of operators as layers.
- DatasetShapes is replaced by OperatorShapes.
- Adopted test_neuraloperator.
- Fix all other occurrences of DatasetShapes.
=> Cleanup: Generalize neural operator and introduce OperatorShapes

CHANGELOG.md, pyproject.toml
This PR updates the version requirements from a fixed version to a more flexible, yet controlled, version range for required packages. Namely:
- torch "==2.1.0" -> ">=2.1.0,<3.0.0"
- dataptation "==3.1" -> ">=3.1,<4.0"
- optuna "==3.5.0" -> ">=3.5.0,<4.0.0"
This change aims to balance the need for adaptability with our ability to test this package reliably.
- Rocm accelerated torch is not provided for version 2.1.0.
- Torch deletes cuda dependencies for version 2.1.0 with Poetry (even when Continuity is used as a dependency).
- It is discuraged to use "overly strict" dependency versions when a package is used as a library [[setuptools](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html)]. And I think this should be the goal of this project.
- Adapts versions of packages: …
=> Feature: Required package version requirements lock major

src/continuity/operators/neuraloperator.py, tests/operators/test_neuraloperator.py
- NeuralOperator doesn't use y
- Use last layer to evaluate in y.
- Tested using operator shapes test.
=> Bugfix: Use last layer to evaluate.

.github/actions/setup-venv/action.yml
This pr fixes minor issues with the CI venve cache id string.
- When multiple optional dependencies are provided the venv caching does not work anymore as the string-id does not allow for ',' characters inside it.
- The python version was not used from the input and the value was not used.
- Introduces step to cleanup the raw ID by removing '[],' characters from the raw ID.
- Uses `inputs.python-version` instead of `matrix.python-version`.
- CI runs without any new errors.
=> Bugfix: CI venv cache ID

.github/workflows/docs.yml, .github/workflows/test.yml
This pr removes the `setup-venv` action from the CI pipelines due to an error with caching.
- Currently Python versions 3.9 and 3.10 are not properly setup on MacOS (confirmed on these ones). The venv is pulled from cache but does not contain the correct dependencies.
- Changes pipelines to not use the `setup-venv` action.
- Uses cached pip dependencies instead.
- The pipeline now runs without issues.
=> Hotfix: CI pipeline venv

src/continuity/trainer/callbacks.py, src/continuity/trainer/trainer.py, tests/trainer/test_trainer.py
- Trainer is a general training loop implementation, but does not work with standard torch models.
- Adapts only a few lines in `Trainer.fit` such that we can also train torch models with it.
- Fixes the PrintTrainingLoss to print the current test loss (which is also used for stopping criterion).
- Added test_trainer_with_torch_model.
=> Make Trainer usable with standard torch model.

CHANGELOG.md, src/continuity/transforms/__init__.py, src/continuity/transforms/quantile_scaler.py, tests/transforms/test_quantile_scaler.py
This pr introduces a quantile based scaler. The `QuantileScaler` class introduced in this PR provides a robust method for scaling features to a target distribution using quantile information. This approach is particularly useful for datasets with outliers or non-normal distributions. It maps n quantile intervals of the source distribution onto n quantile intervals of a Gaussian distribution. This preserves the internal structure of the data while allowing for applying different transformations depending on the quantile interval.
- Common Min-Max/Mean scalers are not robust to outliers and multiple scales.
- Implements `QuantileScaler`class.
- Added unit-tests for `QuantileScaler`.
=> Feature: Quantile Scaler

src/continuity/transforms/quantile_scaler.py, src/continuity/transforms/scaling.py
This pr introduces the torch tensor class `Parameter` to Transform classes. When moving `nn.Module` instances to device it only moves designated parameters to the device. Common `torch.Tensor` instances do not belong to this class. `torch.nn.Parameter` fixes this issue.
- Transform instances parameters not moved to device.
- Fixes #117
- Introduces `nn.Parameter` tensors to already implemented transformations (for relevant attributes).
- Unit tests run without new errors.
- Ran locally on `cuda`.
=> Fix: Transformations Not Properly Working When Moved to Device

.github/workflows/docs.yml, .github/workflows/test.yml, CONTRIBUTING.md, benchmarks/README.md, pyproject.toml
- We split the dependencies into default, [docs], [testing], [benchmark] and that becomes confusing.
- Split only into default (including [benchmark]) and dev (including [docs] and [testing])
- As before.
=> Split dependencies only into standard and dev.

benchmarks/results/process.py
=> Feature: Load data benchmark results

pyproject.toml, src/continuiti/__init__.py, tests/benchmarks/run/test_runner.py, tests/benchmarks/test_navierstokes.py, tests/pde/deepxde_example.py, tests/pde/test_deepxde.py, tests/pde/test_pideeponet.py, tests/trainer/test_trainer.py
- There is no minimal example for PI-DeepONet.
- Implements the example from DeepXDE in continuiti.
- Added test_deepxde and test_pideeponet.
=> Add 1D Poisson PI-DeepONet example as in DeepXDE.

.gitignore, data/README.md, pyproject.toml
- We have too many dependencies, many of them are actually optional or only needed for dev/testing.
- Move several dependencies into dev.
- Locally: I am able to run `benchmarks/run_single.py` after `pip install -e .` only.
- All tests run as before with `pip install -e .[dev]`
=> Feature: Reduce non-optional dependencies

pyproject.toml
DeepXDE has scikit-learn as an upstream dependency. scikit-learn changed the file path to a specific method (https://github.com/scikit-learn/scikit-learn/commit/e125e67bce7811eefb6f449918dc6aba596678ee) causing this error. The error has been fixed in DeepXDE (https://github.com/lululxvi/deepxde/pull/1760) but still persists in the current release of DeepXDE. This issue exists for over two weeks now.
Once this issue has been addressed in the upstream package or a new release of DeepXDE is available this dependency can and should be removed again.
- Upstream dependency is broken.
- Limits the version of the broken package.
- no new errors are introduced.
=> Bugfix: Broken Upstream Dependency

CHANGELOG.md, src/continuiti/networks/__init__.py, src/continuiti/networks/attention.py, src/continuiti/networks/multi_head_attention.py, src/continuiti/networks/scaled_dot_product_attention.py, tests/networks/test_multi_head.py, tests/networks/test_scaled_dot.py
This PR introduces multi-head attention as described in "Attention is All you Need" paper (https://proceedings.neurips.cc/paper/2017/file/3f5ee243547dee91fbd053c1c4a845aa-Paper.pdf) with bias for projection mappings.
This pr introduces a sub-module to Continuity that specifically deals with implementations of common networks and structures used for implementations of operators but not operators themselves (neural networks, attention, ...).
- The torch implementation of multi-head-attention always defaults to scaled-dot-product attention (https://github.com/pytorch/pytorch/blob/main/torch/nn/functional.py).
- Multi-head attention with flexible attention implementation.
- Added Unit tests for `MultiHeadAttention`.
=> Feature: Multi-Head Attention

CHANGELOG.md, src/continuiti/operators/operator.py
Masked operators are able to apply masks during the forward pass to selectively use or ignore parts of the input. While the current `Operator` implementation usually allows to use various numbers of evaluation points, if fails to facilitate this behavior for differing numbers of sensors. While some operators are able to handle this behavior batched inputs are necessary to promote efficient and stable training. Therefore, masked inputs, allowing for padding sequences are required.
This PR introduces two new operator classes `MaskedOperator`. The `MaskedOperator` is able to process masked inputs by additionally accepting masks during the forward pass.
- Masked inputs cannot be passed to the operator implementation.
- Implements `MaskedOperator` class to allow for masked inputs, that extends …
=> Feature: Masked Operator

CHANGELOG.md, src/continuiti/operators/deeponet.py, tests/operators/test_deeponet.py
- Fixes #71 
- Adds possibility to use custom branch and trunk network in DeepONet by introducing `branch_network` and `trunk_network` arguments.
- Added `test_custom_deeponet`.
=> DeepONet should support arbitrary trunk/branch networks

tests/pde/deepxde_example.py, tests/pde/test_pideeponet.py
As discussed [here](https://github.com/lululxvi/deepxde/issues/1796) does DeepXDE internally set the device context when initializing the pytorch backend (https://deepxde.readthedocs.io/en/latest/user/installation.html#pytorch-backend).
This results in errors when running the tests with more than one device. The device context for iterators and instances such as the torch dataloader conflicts. 
- Not all unit tests running on machines with multiple devices, due to device context initialization of DeepXDE.
- Isolates the deepxde import from the rest of the test-code.
- All unit tests run without new errors.
=> Fix: Test failing when using DeepXDE
